export const DISPLAY_ALL_BOARDS = "DISPLAY_ALL_BOARDS";
export const REQUEST_ALL_BOARDS = "REQUEST_ALL_BOARDS";

export const DISPLAY_ALL_LISTS = "DISPLAY_ALL_LISTS";
export const ADD_NEW_LIST = "ADD_NEW_LIST";
export const REQUEST_DISPLAY_ALL_LISTS = "REQUEST_DISPLAY_ALL_LISTS";
export const  REQUEST_ADD_NEW_LIST = "REQUEST_ADD_NEW_LIST";

export const DISPLAY_ALL_CARDS = "DISPLAY_ALL_CARDS";
export const ADD_NEW_CARD = "ADD_NEW_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const REQUEST_CARDS ="REQUEST_CARDS"
export const REQUEST_ADD_NEW_CARD = "REQUEST_ADD_NEW_CARD";
export const REQUEST_DELETE_CARD = "REQUEST_DELETE_CARD";

export const DISPLAY_CHECKLIST = "DISPLAY_CHECKLIST"
export const ADD_CHECKLIST = "ADD_CHECKLIST"
export const DELETE_CHECKLIST = "DELETE_CHECKLIST"
export const REQUEST_DISPLAY_CHECKLIST = "REQUEST_DISPLAY_CHECKLIST"
export const REQUEST_ADD_CHECKLIST = "REQUEST_ADD_CHECKLIST"
export const REQUEST_DELETE_CHECKLIST = "REQUEST_DELETE_CHECKLIST"

export const ADD_CHECKITEM = "ADD_CHECKITEM"
export const DELETE_CHECKITEM = "DELETE_CHECKITEM"
export const UPDATE_CHECKITEM = "UPDATE_CHECKITEM"
export const REQUEST_ADD_CHECKITEM = "REQUEST_ADD_CHECKITEM"
export const REQUEST_DELETE_CHECKITEM = "REQUEST_DELETE_CHECKITEM"
export const REQUEST_UPDATE_CHECKITEM = "REQUEST_UPDATE_CHECKITEM"

